name: sham_cars
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1
  flutter: '>=3.38.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.4
  equatable: ^2.0.5
  faker: ^2.2.0
  logger: ^2.4.0
  go_router: ^17.0.0
  flutter_svg: ^2.2.0
  flutter_localizations:
    sdk: flutter
  intl: any
  extended_masked_text: ^3.0.1
  flutter_native_splash: ^2.4.2
  http: ^1.3.0
  cronet_http: ^1.3.2
  get_it: ^8.0.2
  skeletonizer: ^2.0.0
  fetch_client: ^1.1.2
  flutter_secure_storage: ^10.0.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  go_router_builder: ^4.1.3
  build_runner: ^2.10.0
  build_verify: any
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
    - family: inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 700